[package]
name = "cloudflare-ddns"
version = "0.1.0"
edition = "2021"

[dependencies]
ureq = { version = "2.8", features = ["json"] }
serde = { version = "1.0", features = ["derive"] }
thiserror = "1.0"
dotenvy = "0.15"
